### ISSUE TITLE
NoClassDefFoundError on startup

### ISSUE THREAD

**Issue by fabianmakila** [4drian3d/VLobby#33]
I'm getting this error when starting the plugin:

```
[20:49:31] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to vlobby
java.lang.NoClassDefFoundError: io/github/_4drian3d/vlobby/libs/org/spongepowered/configurate/hocon/HoconConfigurationLoader
	at io.github._4drian3d.vlobby.VLobby.onProxyInitialization(VLobby.kt:77) ~[?:?]
	at io.github._4drian3d.vlobby.Lmbda$10.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: io.github._4drian3d.vlobby.libs.org.spongepowered.configurate.hocon.HoconConfigurationLoader
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64) ~[velocity.jar:3.2.0-SNAPSHOT (git-40b76c63-b256)]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more
```

This only affects VLobby version `2.0.1`, the earlier version `2.0.0` is working as expected.

## Version information
VLobby: `2.0.1`
Velocity: `3.2.0-SNAPSHOT (git-40b76c63-b256)`

**Comment by 4drian3d** [comment]
Delete the `vlobby/libs` folder

**Comment by fabianmakila** [comment]
That seems to have fixed it. Closing this as completed.
